version: '2.2'
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker/php/php.override.ini:/usr/local/etc/php/conf.d/php.override.ini
    networks:
      - app-network

  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - "./docker/mysql/data:/var/lib/mysql:rw"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
